apiVersion: v1
kind: Service
metadata:
  name: gestion-biblio-service
  labels:
    app: gestion-biblio-app 
spec:
  selector:
    app: gestion-biblio-app

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer
